---
- name: Download GO's linux installer
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{go_version}}.linux-amd64.tar.gz
    dest: /tmp
- name: Delete previous installation
  command: rm -rf /usr/local/go
- name: Extract the go archive into /usr/local
  ansible.builtin.shell: tar -C /usr/local -xzf go{{go_version}}.linux-amd64.tar.gz
  args:
    chdir: /tmp
- name: Add go binary path to ~/.profile
  lineinfile:
    path: ~/.profile
    line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
    create: true
    state: present
- name: Source updated profile and test go version
  shell: . ~/.profile && go version