---
- name: Update the apt package index
  apt:
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install apt-transport-https
  apt:
    pkg:
      - apt-transport-https
    state: latest
    update_cache: true

- name: Add an apt signing key for Kubernetes  
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Update the apt package index
  apt:
    update_cache: yes 
    force_apt_get: yes
    cache_valid_time: 3600

- name: Disable Swap Memory
  shell: swapoff -a

- name: Install kubelet
  ansible.builtin.apt:
    name: kubelet={{ kubernetes_version }}
    state: present
    update_cache: true

- name: Install kubeadm
  ansible.builtin.apt:
    name: kubeadm={{ kubernetes_version }}
    state: present
    update_cache: true

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl={{ kubernetes_version }}
    state: present
    update_cache: true

# We configure hold on kubeadm, kubectl and kubelet packages 
# in order to make sure that are not accidentally
# upgrated or removed  

- name: Hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold