---
- name: Download helm-v3.5.0-linux-amd64.tar.gz
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.5.0-linux-amd64.tar.gz
    dest: /tmp/helm-v3.5.0-linux-amd64.tar.gz

- name: Extract helm-v3.5.0-linux-amd64.tar.gz into /tmp
  ansible.builtin.unarchive:
    src: /tmp/helm-v3.5.0-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy helm executable
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    owner: ubuntu
    group: ubuntu
    remote_src: yes


