---
- name: copy kubeadm-config.yaml from ansible control node to k8s master node
  template:
    src: kubeadm-config.yaml
    dest: /tmp

- name: Initialize kubeadm
  ansible.builtin.shell: kubeadm init --config /tmp/kubeadm-config.yaml

- name: populate /etc/environment with KUBECONFIG variable
  lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"


